backend:
  name: github
  repo: ntohq/education-path
  branch: dev

media_folder: public/img
public_folder: /img

collections:
  - name: 'news'
    label: 'News Posts'
    folder: '/src/client/content/news'
    format: 'frontmatter'
    create: true
    slug: '{{title}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Pexel Image', name: 'img', widget: 'image' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Description', name: 'clentcher', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }